### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by jonocarroll** [AU-BURGr/ozdata#1]
- [ ] package structure
- [ ] connect to API (`ckanr`)
- [ ] pull some data from `data.gov.au`
- [ ] generalise function to pull data from `data.gov.au`
- [ ] pull some data from `ozmacrodata.org`
- [ ] generalise function to pull data from `ozmacrodata.org`
- [ ] convert data to `sf` for plotting
- [ ] documentation
- [ ] vignette
